apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-tunnel-panel.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "edge-tunnel-panel.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
